<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TASHTIP.EF2\TASHTIP.EF.csproj" />
    <ProjectReference Include="..\TASHTIP.InfraDB2\TASHTIP.InfraDB.csproj" />
  </ItemGroup>

</Project>
